apiVersion: platform.local.lab/v1alpha1
kind: XRestApi
metadata:
  name: hello-world-rest-api
spec:
  namespace: hello-world-rest-api
  goVersion: "1.22"
  s3:
    enabled: true
  elasticache:
    enabled: true
