apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 83.4.0
    helm:
      releaseName: monitoring
      values: |
        kubeApiServer:
          enabled: false
        grafana:
          serviceMonitor:
            enabled: false
        prometheusOperator:
          serviceMonitor:
            selfMonitor: false
        alertmanager:
          alertmanagerSpec:
            nodeSelector:
              node-role.kubernetes.io/worker: worker
            storage:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 5Gi
        grafana:
          nodeSelector:
            node-role.kubernetes.io/worker: worker
          deploymentStrategy:
            type: Recreate
          admin:
            existingSecret: grafana-admin-secret
            userKey: admin-user
            passwordKey: admin-password
          grafana.ini:
            auth:
              anonymous:
                enabled: true
                org_role: Viewer
            auth.anonymous:
              enabled: true
              org_role: Viewer
          persistence:
            enabled: true
            size: 5Gi
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki.monitoring.svc.cluster.local:3100
              access: proxy
              isDefault: false
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 384Mi
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: ALL
              folderAnnotation: grafana_folder
              provider:
                foldersFromFilesStructure: true
          ingress:
            enabled: false
        prometheus:
          prometheusSpec:
            nodeSelector:
              node-role.kubernetes.io/worker: worker
            retention: 30d
            scrapeInterval: "60s"
            evaluationInterval: "60s"
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 1500Mi
            storageSpec:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 20Gi
          ingress:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
