# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.30.0
    helm:
      releaseName: loki
      values: |
        deploymentMode: SingleBinary
        loki:
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          auth_enabled: false
          limits_config:
            retention_period: 30d
          compactor:
            retention_enabled: true
            delete_request_store: filesystem
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 10Gi
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        gateway:
          enabled: false
        lokiCanary:
          enabled: false
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
