apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-exporter
  namespace: platform-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-exporter
  template:
    metadata:
      labels:
        app: platform-exporter
    spec:
      serviceAccountName: platform-exporter
      containers:
        - name: platform-exporter
          image: ghcr.io/cujarrett/platform-exporter:sha-b29fa500613ecfd80236a8c2c99e2e6647bb858b
          ports:
            - name: metrics
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: platform-exporter
  namespace: platform-exporter
  labels:
    app: platform-exporter
spec:
  selector:
    app: platform-exporter
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
