apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ghost.yaml
  - ghost-backup.yaml
configMapGenerator:
  - name: ghost-backup-script
    namespace: blog
    files:
      - backup.py=ghost-backup.py
generatorOptions:
  disableNameSuffixHash: true
