apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz
  namespace: argocd
spec:
  project: cluster
  sources:
    - repoURL: https://helm.linkerd.io/edge
      chart: linkerd-viz
      targetRevision: 2025.12.3
      helm:
        releaseName: linkerd-viz
        values: |
          prometheus:
            enabled: false
          prometheusUrl: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-viz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
