apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: xrs
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/cujarrett/homelab-workspaces.git
        revision: main
        requeueAfterSeconds: 60
        directories:
          - path: "*"
          - path: ".github"
            exclude: true
  template:
    metadata:
      name: "{{path.basename}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      revisionHistoryLimit: 5
      project: workloads
      source:
        repoURL: https://github.com/cujarrett/homelab-workspaces.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - allowEmpty=true
