apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane:compose-wordpress
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups: [""]
    resources: ["secrets", "services", "persistentvolumeclaims", "namespaces", "configmaps"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: ["traefik.io"]
    resources: ["middlewares", "ingressroutes"]
    verbs: ["*"]
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["*"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors", "servicemonitors/status"]
    verbs: ["*"]
