apiVersion: v1
kind: Namespace
metadata:
  name: secret-mirror-controller
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
