apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: my-vinyl-api
spec:
  image: ghcr.io/cujarrett/my-vinyl-api:main
  port: 8080
  environment: test
  cache:
    enabled: true
  secretRef:
    name: discogs-credentials
