{
 "title": "Web Traffic - Kiosk",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "blog.mattjarrett.dev",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=~\"blog-ghost.*@kubernetes\"}[24h]))",
     "legendFormat": "requests 24h"
    }
   ]
  },
  {
   "title": "mattjarrett.dev",
   "type": "stat",
   "gridPos": { "x": 3, "y": 0, "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=~\"mattjarrett-dev-mattjarrett-dev.*@kubernetes|web-mattjarrett-dev.*@kubernetes\"}[24h]))",
     "legendFormat": "requests 24h"
    }
   ]
  },
  {
   "title": "myvinyl.mattjarrett.dev",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=~\"my-vinyl-my-vinyl.*@kubernetes\"}[24h]))",
     "legendFormat": "requests 24h"
    }
   ]
  },
  {
   "title": "jspollock.mattjarrett.dev",
   "type": "stat",
   "gridPos": { "x": 9, "y": 0, "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=~\"js-pollock-js-pollock.*@kubernetes\"}[24h]))",
     "legendFormat": "requests 24h"
    }
   ]
  },
  {
   "title": "launchpad.mattjarrett.dev",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 3, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=~\"launchpad-launchpad.*@kubernetes\"}[24h]))",
     "legendFormat": "requests 24h"
    }
   ]
  },
  {
   "title": "Requests / hr - All Sites",
   "type": "timeseries",
   "gridPos": { "x": 15, "y": 0, "w": 9, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=~\"blog-ghost.*@kubernetes\"}[1h]))",
     "legendFormat": "blog"
    },
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=~\"mattjarrett-dev-mattjarrett-dev.*@kubernetes|web-mattjarrett-dev.*@kubernetes\"}[1h]))",
     "legendFormat": "mattjarrett.dev"
    },
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=~\"my-vinyl-my-vinyl.*@kubernetes\"}[1h]))",
     "legendFormat": "myvinyl"
    },
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=~\"js-pollock-js-pollock.*@kubernetes\"}[1h]))",
     "legendFormat": "jspollock"
    },
    {
     "expr": "sum(increase(traefik_service_requests_total{exported_service=~\"launchpad-launchpad.*@kubernetes\"}[1h]))",
     "legendFormat": "launchpad"
    }
   ]
  }
 ]
}