apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-playlist-kiosk
  namespace: monitoring
data:
  kiosk.yaml: |
    apiVersion: 1
    playlists:
      - uid: bfkvgx130fncwc
        name: Kiosk
        interval: 30s
        items:
          - type: dashboard_by_uid
            value: homelab-kiosk
          - type: dashboard_by_uid
            value: web-traffic-kiosk
