apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 87.4.0
    helm:
      releaseName: monitoring
      values: |
        kubeApiServer:
          enabled: false
        kubelet:
          serviceMonitor:
            metricRelabelings:
              - sourceLabels: [__name__]
                regex: "apiserver_.+|etcd_.+|workqueue_.+_bucket|prober_.+_bucket|scheduler_.+_bucket|kubelet_runtime_operations_duration_seconds_bucket|container_blkio_device_usage_total|storage_operation_duration_seconds_bucket|rest_client_request_duration_seconds_bucket|kubernetes_feature_enabled"
                action: drop
        prometheusOperator:
          serviceMonitor:
            selfMonitor: false
          admissionWebhooks:
            patch: {}
        alertmanager:
          alertmanagerSpec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node-role.kubernetes.io/control-plane
                          operator: DoesNotExist
            storage:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 2Gi
        grafana:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: DoesNotExist
          plugins:
            - marcusolsson-treemap-panel
          serviceMonitor:
            enabled: false
          deploymentStrategy:
            type: Recreate
          admin:
            existingSecret: grafana-admin-secret
            userKey: admin-user
            passwordKey: admin-password
          grafana.ini:
            auth:
              anonymous:
                enabled: true
                org_role: Viewer
            auth.anonymous:
              enabled: true
              org_role: Viewer
          persistence:
            enabled: true
            size: 2Gi
            storageClassName: longhorn
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki.monitoring.svc.cluster.local:3100
              access: proxy
              isDefault: false
            - name: Sump Pump Archive
              uid: sump-pump-archive
              type: prometheus
              url: http://prometheus-sump-pump.monitoring.svc.cluster.local:9090
              access: proxy
              isDefault: false
          resources:
            requests:
              memory: 1024Mi
            limits:
              memory: 1536Mi
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: ALL
              folderAnnotation: grafana_folder
              provider:
                foldersFromFilesStructure: true
                allowUiUpdates: true
          ingress:
            enabled: false
        prometheus:
          prometheusSpec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node-role.kubernetes.io/control-plane
                          operator: DoesNotExist
            enableAdminAPI: true
            retention: 30d
            retentionSize: 32GB
            scrapeInterval: "60s"
            evaluationInterval: "60s"
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 1500Mi
            storageSpec:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 35Gi
          ingress:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
