apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: linkerd-controller
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: [linkerd, linkerd-viz]
  selector:
    matchLabels:
      linkerd.io/control-plane-component: controller
  endpoints:
    - port: admin-http
      path: /metrics
