apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/cujarrett/homelab.git
    targetRevision: main
    path: apps/adguard
  destination:
    server: https://kubernetes.default.svc
    namespace: adguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
