apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattjarrett-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cujarrett/homelab.git
    targetRevision: main
    path: apps/mattjarrett-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: mattjarrett-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
