apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattjarrett-com
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cujarrett/homelab.git
    targetRevision: main
    path: platform/xrs/wordpress
    directory:
      include: "mattjarrett-com.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: mattjarrett-com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
