apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-definitions
  namespace: argocd
spec:
  revisionHistoryLimit: 5
  project: platform
  source:
    repoURL: https://github.com/cujarrett/homelab.git
    targetRevision: main
    path: platform
    directory:
      recurse: true
      exclude: "xrs/**"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
